<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PerfilesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::unprepared('INSERT INTO `perfiles` (`id`,`nombre`,`estatus`,`permisos`,`menu`,`tipo_perfil`,`usuario_creacion`,`usuario_modificacion`,`created_at`,`updated_at`) VALUES (1,"Super Usuario",1,"[\"2_1_consultar\",\"2_1_agregar\",\"2_1_editar\",\"2_1_deshabilitar\",\"2_1_exportar\",\"8_5_consultar\",\"8_5_ver_poliza\",\"8_5_ver_detalle\",\"8_5_exportar\",\"8_5_reemplazar_poliza\",\"8_5_reemplazar_archivo_poliza\",\"8_9_consultar\",\"8_9_guardarpoliza\",\"8_9_getdatosconsesiones\",\"8_9_imprimirdatoss\",\"8_9_descargarformato\",\"8_10_desbloqueoconcesion\",\"8_10_desbloqueoconcesionupdate\",\"10_6_consultar\",\"10_6_exportar\"]","[{\"modulo\":1,\"namemodulo\":\"Usuarios\",\"modruta\":\"users\",\"modicono\":null,\"submodulos\":[{\"submodulo\":2,\"namesubmodulo\":\"Usuarios\",\"subruta\":\"users\",\"subicono\":null,\"funciones\":[{\"id\":1,\"nombre\":\"Usuarios\",\"ruta\":\"users\",\"icono\":null,\"orden\":1}]}]},{\"modulo\":7,\"namemodulo\":\"Concesiones\",\"modruta\":\"consultaradeudoconsescion\",\"modicono\":null,\"submodulos\":[{\"submodulo\":8,\"namesubmodulo\":\"Concesiones\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":5,\"nombre\":\"Administrador de concesiones\",\"ruta\":\"admin_concesiones\",\"icono\":null,\"orden\":0},{\"id\":9,\"nombre\":\"Consulta de concesiones\",\"ruta\":\"consultaradeudoconsescion\",\"icono\":null,\"orden\":1},{\"id\":10,\"nombre\":\"Desbloqueo de concesiones\",\"ruta\":\"desbloqueoconcesion\",\"icono\":null,\"orden\":2}]}]},{\"modulo\":9,\"namemodulo\":\"Reportes\",\"modruta\":null,\"modicono\":null,\"submodulos\":[{\"submodulo\":10,\"namesubmodulo\":\"Reportes\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":6,\"nombre\":\"Reporte de pólizas de seguro por concesión\",\"ruta\":\"reporte_polizas_x_concesion\",\"icono\":null,\"orden\":0}]}]}]","g","admin",NULL,NOW(),NULL)');
        DB::unprepared('INSERT INTO `perfiles` (`id`,`nombre`,`estatus`,`permisos`,`menu`,`tipo_perfil`,`usuario_creacion`,`usuario_modificacion`,`created_at`,`updated_at`) VALUES (2,"Monitor",1,"[\"2_1_consultar\",\"8_5_consultar\",\"8_5_exportar\",\"10_6_consultar\",\"10_6_exportar\"]","[{\"modulo\":1,\"namemodulo\":\"Usuarios\",\"modruta\":\"users\",\"modicono\":null,\"submodulos\":[{\"submodulo\":2,\"namesubmodulo\":\"Usuarios\",\"subruta\":\"users\",\"subicono\":null,\"funciones\":[{\"id\":1,\"nombre\":\"Usuarios\",\"ruta\":\"users\",\"icono\":null,\"orden\":1}]}]},{\"modulo\":7,\"namemodulo\":\"Concesiones\",\"modruta\":null,\"modicono\":null,\"submodulos\":[{\"submodulo\":8,\"namesubmodulo\":\"Concesiones\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":5,\"nombre\":\"Administrador de concesiones\",\"ruta\":\"admin_concesiones\",\"icono\":null,\"orden\":0}]}]},{\"modulo\":9,\"namemodulo\":\"Reportes\",\"modruta\":null,\"modicono\":null,\"submodulos\":[{\"submodulo\":10,\"namesubmodulo\":\"Reportes\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":6,\"nombre\":\"Reporte de pólizas de seguro por concesión\",\"ruta\":\"reporte_polizas_x_concesion\",\"icono\":null,\"orden\":0}]}]}]","g","admin",NULL,NOW(),NULL)');
        DB::unprepared('INSERT INTO `perfiles` (`id`,`nombre`,`estatus`,`permisos`,`menu`,`tipo_perfil`,`usuario_creacion`,`usuario_modificacion`,`created_at`,`updated_at`) VALUES (3,"Analista",1,"[\"8_5_consultar\",\"8_5_ver_poliza\",\"8_5_ver_detalle\",\"8_5_exportar\",\"8_5_reemplazar_poliza\",\"8_5_reemplazar_archivo_poliza\",\"8_9_consultar\",\"8_9_guardarpoliza\",\"8_9_getdatosconsesiones\",\"8_9_imprimirdatoss\",\"8_9_descargarformato\",\"8_10_desbloqueoconcesion\",\"8_10_desbloqueoconcesionupdate\",\"10_6_consultar\",\"10_6_exportar\"]","[{\"modulo\":7,\"namemodulo\":\"Concesiones\",\"modruta\":\"consultaradeudoconsescion\",\"modicono\":null,\"submodulos\":[{\"submodulo\":8,\"namesubmodulo\":\"Concesiones\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":5,\"nombre\":\"Administrador de concesiones\",\"ruta\":\"admin_concesiones\",\"icono\":null,\"orden\":0},{\"id\":9,\"nombre\":\"Consulta de concesiones\",\"ruta\":\"consultaradeudoconsescion\",\"icono\":null,\"orden\":1},{\"id\":10,\"nombre\":\"Desbloqueo de concesiones\",\"ruta\":\"desbloqueoconcesion\",\"icono\":null,\"orden\":2}]}]},{\"modulo\":9,\"namemodulo\":\"Reportes\",\"modruta\":null,\"modicono\":null,\"submodulos\":[{\"submodulo\":10,\"namesubmodulo\":\"Reportes\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":6,\"nombre\":\"Reporte de pólizas de seguro por concesión\",\"ruta\":\"reporte_polizas_x_concesion\",\"icono\":null,\"orden\":0}]}]}]","g","admin",NULL,NOW(),NULL)');
        DB::unprepared('INSERT INTO `perfiles` (`id`,`nombre`,`estatus`,`permisos`,`menu`,`tipo_perfil`,`usuario_creacion`,`usuario_modificacion`,`created_at`,`updated_at`) VALUES (4,"Control",1,"[\"4_2_consultar\",\"4_2_agregar\",\"4_2_editar\",\"4_2_deshabilitar\",\"4_3_consultar\",\"4_3_agregar\",\"4_3_editar\",\"4_3_deshabilitar\",\"4_4_consultar\",\"4_4_agregar\",\"4_4_editar\",\"4_4_deshabilitar\",\"5_7_mostrar\",\"5_8_ver_logs\"]","[{\"modulo\":3,\"namemodulo\":\"Configuraciones\",\"modruta\":\"configuraciones\",\"modicono\":null,\"submodulos\":[{\"submodulo\":4,\"namesubmodulo\":\"Permisos\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":2,\"nombre\":\"Modulos\",\"ruta\":\"modulos\",\"icono\":null,\"orden\":1},{\"id\":3,\"nombre\":\"Funciones\",\"ruta\":\"funciones\",\"icono\":null,\"orden\":2},{\"id\":4,\"nombre\":\"Perfiles\",\"ruta\":\"perfiles\",\"icono\":null,\"orden\":3}]},{\"submodulo\":5,\"namesubmodulo\":\"Bitacora de accesos\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":7,\"nombre\":\"Bitácora\",\"ruta\":\"bitacoras\",\"icono\":null,\"orden\":0},{\"id\":8,\"nombre\":\"Logs\",\"ruta\":\"viewLogs\",\"icono\":null,\"orden\":0}]}]}]","g","admin",NULL,NOW(),NULL)');
        DB::unprepared('INSERT INTO `perfiles` (`id`,`nombre`,`estatus`,`permisos`,`menu`,`tipo_perfil`,`usuario_creacion`,`usuario_modificacion`,`created_at`,`updated_at`) VALUES (5,"Ventanilla",1,"[\"8_9_consultar\",\"8_9_guardarpoliza\",\"8_9_getdatosconsesiones\",\"8_9_imprimirdatoss\",\"8_9_descargarformato\"]","[{\"modulo\":7,\"namemodulo\":\"Concesiones\",\"modruta\":\"consultaradeudoconsescion\",\"modicono\":null,\"submodulos\":[{\"submodulo\":8,\"namesubmodulo\":\"Concesiones\",\"subruta\":null,\"subicono\":null,\"funciones\":[{\"id\":9,\"nombre\":\"Consulta de concesiones\",\"ruta\":\"consultaradeudoconsescion\",\"icono\":null,\"orden\":1}]}]}]","g","admin",NULL,NOW(),NULL)');
    }
}
